### ISSUE TITLE
Feature request: Clock

### ISSUE THREAD

**Issue by Koepel** [RobTillaart/TM1637_RT#24]
Would it be possible to make a clock function with a optional ':' in the middle ?
With two integers and a boolean variable for the middle ':'.
It is the most common use of the display and the hardest to make with the library.

**Comment by RobTillaart** [comment]
Thanks for the issue, will come back to it later this week.

**Comment by RobTillaart** [comment]
@Koepel 
something like 
```cpp
void displayTime(uint8_t hh, uint8_t mm, bool)
```

**Comment by RobTillaart** [comment]
@Koepel 
for 4 digit display only
```cpp
void TM1637::displayTime(uint8_t hh, uint8_t mm, bool colon)
{
  if (_digits != 4) return;
  uint8_t data[4] = { 16, 16, 16, 16 };
  data[3] = hh / 10;
  data[2] = hh % 10;
  data[1] = mm / 10;
  data[0] = mm % 10;
  displayRaw(data, colon ? 2 : -1);
}
```

in my first measurements one call takes 1352 micros (UNO, 1.8.19).

I will make a PR asap.

**Comment by RobTillaart** [comment]
@Koepel 

created develop branch.

**Comment by Koepel** [comment]
Thank you, working very well.
This is my test project in Wokwi simulation: https://wokwi.com/projects/356661328560439297

**Comment by RobTillaart** [comment]
Nice demo, may I add the link in the readme?

A question that popped up "is there a way to control multiple displays with less pins" nice one to investigate.

Will merge the PR this evening (its almost 20:00 here)

**Comment by RobTillaart** [comment]
@Koepel 
Merged and released 0.3.6

**Comment by Koepel** [comment]
My goal is to make an example for this page: https://docs.wokwi.com/parts/wokwi-tm1637-7segment#simulator-examples
You can add it to the readme file, but I will make changes. For example using the Library Manager instead of the source files.

**Comment by RobTillaart** [comment]
Made a sketch that display's 1/100th of second. Good for timing 0 to 100 (ok 99,99) second.

Simple game - press reset at 10:00 sharp.

```cpp
//
//    FILE: TM1637_displayTime2.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo TM1637 library
//     URL: https://github.com/RobTillaart/TM1637

#include "TM1637.h"

TM1637 TM;

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);

  TM.begin(7, 6, 4);       //  clockpin, datapin, #digits
}

//  timer with 1/100th of second
void loop()
{
  uint32_t now = (millis() / 10) % 10000;
  uint8_t hh = now / 100;
  uint8_t mm = now - hh * 100;
  bool colon = hh & 1;
  TM.displayTime(hh, mm, colon);
}
```

**Comment by Koepel** [comment]
[My example](https://wokwi.com/projects/356661328560439297) is finished and was added to [the Docs of Wokwi](https://docs.wokwi.com/parts/wokwi-tm1637-7segment#simulator-examples) (the second one "Three TM1637 displays").
