### ISSUE TITLE
Pull up resistors for TM1637 key reading

### ISSUE THREAD

**Issue by SteveMicroCode** [RobTillaart/TM1637_RT#29]
Just a comment after writing some code for the PIC that reads TM1637 keys. It will go on GitHub soon. Your code was an inspiration, useful background.  I see your comments here about using fairly low value pull-ups when reading key data. I use the TM1637 with fairly short lines and no capacitors on clock or data and 10k pull-ups. Looking at the photos I think you had caps in place on the display module. Testing today with a clock period as low as 5us gave no problems in the no cap setup using 10k pull-up resistors. Think that may be why you needed lower value resistors? I think for many uses the 100 pf caps aren’t necessary and should be removed if fitted. If nothing else it avoids the need for a 100us clock period that wastes so much processor time

**Comment by RobTillaart** [comment]
Thanks for your comments,  appreciated!
Need to reread them tomorrow (its too late here to dive into details) .

Need to think how to include this information into the readme.md so people can use them.
Thanks again!

**Comment by SteveMicroCode** [comment]
Glad the comments were constructive!  The datasheet , on which I seem to spot a new randomly placed item every time I read it, says 250kHz clock for applications reading the keys is OK, so you’d think they will have tested at a clock period of sub 5us. Their reference to 100pF caps is vague, they say “can be used”. Bet they didn’t use any caps when testing.  Should read “only use if needed” … Everyone has copied the example schematic slavishly and it seems to be responsible for the entire Arduino world running these chips at worse than a tenth of capacity. I played below the 100us when I used a module with caps and comms went pear shaped very quickly.  Don’t think caps are usually recommended for normal I2C lines. Maybe used for long cables inside a microwave oven :). I laid out a few TM1637 boards of my own and have never put the caps on. My library code is way less fancy than yours, very impressed by what you have done, though I just wanted to do the basics in a small footprint so a 12F PIC can use the display if needed,RegardsSteveSent from my iPadOn 19 Oct 2023, at 21:06, Rob Tillaart ***@***.***> wrote:﻿
Thanks for your comments,  appreciated!
Need to reread them tomorrow (its too late here to dive into details) .
Need to think how to include this information into the readme.md so people can use them.
Thanks again!

**Comment by RobTillaart** [comment]
Finally found some time for the issue. Expect release 0.3.9 soon (mainly documentation)

**Comment by SteveMicroCode** [comment]
That’s great Rob, I will read with interest. My PICs continue to drive the TM1637 well without caps at low single microsecond bit times! Latest connection was over about 15cm hookup wire,SteveSent from my iPadOn 22 Nov 2023, at 16:42, Rob Tillaart ***@***.***> wrote:﻿
Finally found some time for the issue. Expect release 0.3.9 soon (mainly documentation)

**Comment by SteveMicroCode** [comment]
Link to one of my TM1637 related repos, it includes some info on capacitor removal from commercial modules:https://github.com/SteveMicroCode/PIC-TM1637-Library-CodeOn 22 Nov 2023, at 16:42, Rob Tillaart ***@***.***> wrote:﻿
Finally found some time for the issue. Expect release 0.3.9 soon (mainly documentation)

**Comment by RobTillaart** [comment]
Thanks for the info,

Updated readme.md in the develop branch, including a section **Hardware connection and performance**
Most important things are mentioned with a reference to your test.

Thanks again!

**Comment by SteveMicroCode** [comment]
No probSomehow the link to my repo got mashed, here it is:https://github.com/SteveMicroCode/PIC-TM1637-Library-CodeSteveOn 22 Nov 2023, at 21:02, Rob Tillaart ***@***.***> wrote:﻿
Thanks for the info,
Updated readme.md in the develop branch, including a section Hardware connection and performance
Most important things are mentioned with a reference to your test.
Thanks again!

**Comment by SteveMicroCode** [comment]
It happened again!

Trying once more:

https://github.com/SteveMicroCode/PIC-TM1637-Library-Code
