### ISSUE TITLE
Nothing showing up - ESP32

### ISSUE THREAD

**Issue by Niv1900** [RobTillaart/TM1637_RT#3]
Hello @RobTillaart, 

This is a really nice project, as a beginner I always have trouble to use [my 6 digit 7 segments TM1637 display](https://aliexpress.com/item/1005001530959875.html?spm=a2g0o.productlist.0.0.4e88699bzq9ihL&algo_pvid=8251fdfb-7039-43e0-b806-379364312381&algo_expid=8251fdfb-7039-43e0-b806-379364312381-0&btsid=2100bdf016185993786984764e08be&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_). 

I tried the [float example ](https://github.com/RobTillaart/TM1637_RT/blob/master/examples/TM1637_float/TM1637_float.ino) but nothing is showing up. 

I tried on my ESP-WROOM-32 DevBoard, the integration of the library was perfect. I'm using GPIO 26 (CLK) and GPIO 25 (DIO). 

Could I be forgetting something ? Did I fried my 3 test display 🤦 ? 

Sorry that this first issue is a n00b issue...

**Comment by RobTillaart** [comment]
Hi,

The lib is still experimental an tested by me quite some time ago. Think I tested with an UNO as that is my primary platform, but it might have been even a year ago. 
In fact I published this library today (as experimental) after this issue on another lib was posted. - https://github.com/RobTillaart/PCF8574/issues/18  - So I did not verify it recently.

Back to your problem. Some questions.
- do you apply 5V or 3V3 to the display you use?  ESP32, I assume 3V3 .   (performance wise it should work)
- do you have an UNO to verify the working on a 5V platform

The ESP has a 5V pin so you could connect the VCC of the display to that. 
That will not blow up the display, but at least the display gets enough power to light up the LEDS...

hope this helps

**Comment by Niv1900** [comment]
Thank you @RobTillaart ! 

I was applying 5V to the TM1637 (Vin from ESP32) but CLK and DIO are 3.3V signal... I'll try on a UNO right away !

**Comment by RobTillaart** [comment]
I expect clk an dio should be fine with 3V3 as these only send the data to the display.

Otherwise you might need - https://www.adafruit.com/product/1875 or similar.

**Comment by Niv1900** [comment]
Well it works quite nicely on my UNO ! Thank you for this lib ! I will definitely try level shifters on the ESP32.

**Comment by RobTillaart** [comment]
Good to hear, thanks for testing!
