### ISSUE TITLE
Correction to my GitHub repo link

### ISSUE THREAD

**Issue by SteveMicroCode** [RobTillaart/TM1637_RT#31]
Sorry to report the link you posted to my GitHub TM1637 stuff should read as below, the emailed reply got mangled in the upload and gives a 404. Hence your .md needs a small edit. Should be:

https://github.com/SteveMicroCode/PIC-TM1637-Library-Code

Steve

**Comment by RobTillaart** [comment]
oops missed that one

**Comment by RobTillaart** [comment]
fixed it in master, will automatically be in next release

**Comment by SteveMicroCode** [comment]
Email to GitHub seems to mangle stuff!  Frustrating.SteveSent from my iPadOn 23 Nov 2023, at 13:31, Rob Tillaart ***@***.***> wrote:﻿
oops missed that one

**Comment by RobTillaart** [comment]
Yes, a well known "feature"

**Comment by RobTillaart** [comment]
As it is fixed in master I will close the issue.
